### ISSUE TITLE
InternalServerError: Request not supported

### ISSUE THREAD

**Issue by artworkad** [ratson/koa-falcor#1]
I am using koa 2.0.0-alpha.7 and when implementing your example I am getting:

```
InternalServerError: Request not supported
      at Object.throw (/playground/node_modules/koa/lib/context.js:91:23)
      at /playground/node_modules/koa-falcor/lib/index.js:50:16
      at dispatch (/playground/node_modules/koa-compose/index.js:43:32)
      at next (/playground/node_modules/koa-compose/index.js:44:18)
      at parseBody.then.body (/playground/node_modules/koa-bodyparser/index.js:74:14)
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Comment by ratson** [comment]
Thanks for reporting, updated the example code to be more close to real use case.
